// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BibGetAll() {
  return window['go']['main']['App']['BibGetAll']();
}

export function BibGetById(arg1) {
  return window['go']['main']['App']['BibGetById'](arg1);
}

export function CloseSession() {
  return window['go']['main']['App']['CloseSession']();
}

export function ComGetAll() {
  return window['go']['main']['App']['ComGetAll']();
}

export function EstAsignarMulta(arg1, arg2) {
  return window['go']['main']['App']['EstAsignarMulta'](arg1, arg2);
}

export function EstCreate(arg1) {
  return window['go']['main']['App']['EstCreate'](arg1);
}

export function EstDelById(arg1) {
  return window['go']['main']['App']['EstDelById'](arg1);
}

export function EstGetAll() {
  return window['go']['main']['App']['EstGetAll']();
}

export function EstRealizarComentario(arg1) {
  return window['go']['main']['App']['EstRealizarComentario'](arg1);
}

export function GetDataSession() {
  return window['go']['main']['App']['GetDataSession']();
}

export function LibCreate(arg1) {
  return window['go']['main']['App']['LibCreate'](arg1);
}

export function LibDelById(arg1) {
  return window['go']['main']['App']['LibDelById'](arg1);
}

export function LibGetAll() {
  return window['go']['main']['App']['LibGetAll']();
}

export function MulGetAll() {
  return window['go']['main']['App']['MulGetAll']();
}

export function MulGetAllMultas() {
  return window['go']['main']['App']['MulGetAllMultas']();
}

export function MulPagarById(arg1) {
  return window['go']['main']['App']['MulPagarById'](arg1);
}

export function OpenBrowser(arg1) {
  return window['go']['main']['App']['OpenBrowser'](arg1);
}

export function PresAsignarMulta(arg1, arg2) {
  return window['go']['main']['App']['PresAsignarMulta'](arg1, arg2);
}

export function PresCreate(arg1) {
  return window['go']['main']['App']['PresCreate'](arg1);
}

export function PresDelById(arg1) {
  return window['go']['main']['App']['PresDelById'](arg1);
}

export function PresGetAll() {
  return window['go']['main']['App']['PresGetAll']();
}

export function PresTerminar(arg1) {
  return window['go']['main']['App']['PresTerminar'](arg1);
}

export function PresVerificar() {
  return window['go']['main']['App']['PresVerificar']();
}
